### ISSUE TITLE
The `auto` under the different settings

### ISSUE THREAD

**Issue by madagiurgiu25** [madagiurgiu25/seqan3_test#7]
Hi @smehringer,

I think I still dont fully comprehend the different auto styles.
What I found was this description:

```
auto         => will copy the vector, but we wanted a reference
auto&        => will only bind to modifiable lvalues
const auto&  => will bind to anything but make it const, giving us const_iterator
const auto&& => will bind only to rvalues
```
Yet for `auto&&` is still very confusing. 
When to use auto&& and when to use auto& for seqan3 library?

**Comment by smehringer** [comment]
I'll try to explain with examples:

## non-const version

```cpp
int a = 5; // normal variable you can bind to

auto copy_a = a;
auto & ref_a = a;
auto && also_ref_a = a;  
// ^^ compiler knows a is not a temporary (rvalue) so it creates a reference and not a copy.
// You say the `&&` is collapsing to `&`
// In this case `auto &` and `auto &&` are both fine and behave the same.
```

```cpp
// we don't have a variable now

auto copy_5 = 5; 
auto & error = 5; // ERROR, does not compile because you cannot bind to a temporary
auto && also_ref_a = 5;  
// ^^ Now this compiles because && can bind to temporaries.
// In this case `auto` and `auto &&` behave the same.
```

In summary: 
* Use `auto` if you sure you want to copy
* Use `auto &` if you sure you can take a reference
* If you are not sure what exactly you get, `auto &&` works well because it makes sure that you only take by value/copy if necessary (2. example) and be reference if you can (1. example)

## const version

Now with const this behaves just a little differently because a **const reference CAN bind temporaries** but a **`const &&` can ONLY bind temporaries**. (not exaclty sure why in the c++ universe right now but I'm sure it has a sane explanation)

So the examples are now this:

```cpp
int a = 5; // normal variable you can bind to

auto const copy_a = a;
auto const & ref_a = a;
auto const && error = a; // ERROR does not compile  
// ^^ compiler knows a is not a temporary (rvalue) so it complains.
```

```cpp
// we don't have a variable now

auto copy_5 = 5; 
auto const & ref_5 = 5;
auto const && also_ref_a = 5;  
// ^^ Now this compiles because && bind to temporaries.
// In this case `auto const` and `auto const &&` behave the same.
```

In summary:
* Use `auto const` if you sure you want to const copy
* Use `auto const &&` If you are sure you are getting a temporary
* If you are not sure what exactly you get, `auto const &` works well because it makes sure that you only take by value/copy if necessary (2. example) and be reference if you can (1. example)

**Comment by madagiurgiu25** [comment]
Thank you @smehringer ! This is very nice written.
So from what I understand:
- a **const** lvalue reference can accept both a lvalue and a rvalue
- a lvalue reference can accept only a lvalue (no temps); to fix this I would need to use the `auto &&`
- the `auto &&` is slower than `auto &`?
- the `auto const &` is slower than `auto const &&`

**Comment by smehringer** [comment]
> Thank you @smehringer ! This is very nice written. So from what I understand:
> 
>     * a **const** lvalue reference can accept both a lvalue and a rvalue

yes

>     * a lvalue reference can accept only a lvalue (no temps); to fix this I would need to use the `auto &&`

yes
 
>     * the `auto &&` is slower than `auto &`?

no because if it binds an lvalue `auto &&` behaves the same as `auto &`. If it's an rvalue and auto && binds it (allocating memory) , well it is technically slower but since you have a temporary there is nothing you can do better anyway.
 
>     * the `auto const &` is slower than `auto const &&`

no. I don't even think comparing the slowness makes sense. It strongly depends on your application. Just remember to capture by reference if you can.

**Comment by madagiurgiu25** [comment]
Thank you @smehringer !
